### ISSUE TITLE
How Can I remove modal footer?

### ISSUE THREAD

**Issue by wangcansunking** [Tradeshift/react-tradeshift-ui#22]
I use `Modal` in my app, and there is a problem that footer shows in the page when I do not config any thing.

my code is 
```
        <Modal
		title={t('xxx')}
		isOpen={props.isOpen}
		onClose={() => props.closeModal()}>
		<div className="Tradeshift UPSReady">
			<main data-ts="Main">
				...
			</main>
		</div>
	</Modal>
```

![image](https://user-images.githubusercontent.com/19563509/33362363-2515b512-d517-11e7-9a01-72f4439b79dd.png)

**Comment by wejendorp** [comment]
Oh I see, I will push a fix for this. We are defaulting the buttons for the modal right now, assuming you would always want to pass in buttons.
